# Generated by Django 5.1.6 on 2025-03-05 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('', ''), ('Audio/Visual Equipment', 'Audio/Visual Equipment'), ('Backup', 'Backup'), ('Copier', 'Copier'), ('Fax', 'Fax'), ('Hardware', 'Hardware'), ('Other', 'Other'), ('Printer', 'Printer'), ('Radios', 'Radios'), ('Security Cameras', 'Security Cameras'), ('Server', 'Server'), ('Scanner', 'Scanner'), ('', ''), ('Connectivity - Network', 'Connectivity - Network'), ('Connectivity - Sonic Wall', 'Connectivity - Sonic Wall'), ('Connectivity - VPN', 'Connectivity - VPN'), ('', ''), ('Cyber Security', 'Cyber Security'), ('', ''), ('Phone - Desk Phone', 'Desk Phone'), ('Phone - Mobile Phone', 'Mobile Phone'), ('', ''), ('Software - CAD', 'Software - CAD'), ('Software - DW Spectrum', 'Software - DW Spectrum'), ('Software - EDOC', 'Software - EDOC'), ('Software - Email', 'Software - Email'), ('Software - Internet Browser', 'Software - Internet Browser'), ('Software - JMS', 'Software - JMS'), ('Software - LGS', 'Software - LGS'), ('Software - MDIS', 'Software - MDIS'), ('Software - NetData', 'Software - NetData'), ('Software - Office', 'Software - Office'), ('Software - RMS', 'Software - RMS'), ('Software - Watchguard', 'Software - Watchguard'), ('Software - Other', 'Software - Other'), ('', ''), ('User Access - Controlled Access', 'User Access - Controlled Access')], max_length=200)),
                ('notes', models.TextField(max_length=5000)),
                ('created_by', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
